bookmark/urls.py
from django.conf.urls import url, include
from django.views.generic import ListView
from bookmark.views import *

urlpatterns = [
    url(r'^$', BookmarkMain.as_view(), name='main'),
    url(r'^list/$', BookmarkLV.as_view(), name='list'),
    url(r'^detail/(?P<pk>[0-9]+)/$',  BookmarkDV.as_view(), name='detail'),

    url(r'^tag/$', BookmarkTV.as_view(), name='tag_cloud'),
    url(r'^tag/(?P<tag>[^/]+(?u))/$', BookmarkTOL.as_view(), name='tag_object_list'),
]

superjang/urls.py
from django.conf.urls import url, include
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^bookmark/', include('bookmark.urls', namespace='bookmark')),
]

bookmark/models.py
from django.db import models
from django.core.urlresolvers import reverse, reverse_lazy
from tagging.fields import TagField

class Bookmark(models.Model):
    title = models.CharField('사이트명', max_length=100, blank=True, null=True)
    url = models.URLField('도메인', unique=True)
    tag = TagField()

    def __str__(self):
        return self.title

    # def get_absolute_url(self):
    #     return reverse('bookmark:index')

bookmark/views.py
from django.shortcuts import render
from django.views.generic import TemplateView, ListView, DetailView
from bookmark.models import Bookmark
from tagging.models import Tag, TaggedItem
from tagging.views import TaggedObjectList

class BookmarkMain(TemplateView):
    template_name = 'bookmark/main.html'

class BookmarkLV(ListView):
    model = Bookmark
    context_object_name = 'bookmark_list'
    template_name = 'bookmark/bookmark_list.html'

class BookmarkDV(DetailView):
    model = Bookmark
    context_object_name = 'bookmark_detail'
    template_name = 'bookmark/bookmark_detail.html'

class BookmarkTV(TemplateView):
    template_name = 'bookmark/tag_cloud.html'


class BookmarkTOL(TaggedObjectList):
    model = Bookmark
    template_name = 'bookmark/tag_list.html'

base/templates/common/base.html
{% load staticfiles %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>{% block title %}BASE Template{% endblock %}</title>
    <link rel="stylesheet" href="{% static "style/common/common.css" %}">
    {% block service_style %}{% endblock %}
</head>
<body>

    <div id="content">
        {% block content %}
        default block
        {% endblock %}
    </div>
</body>
</html>

base/templates/common/footer.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>

</body>
</html>

base/templates/common/header.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>

</body>
</html>

bookmark/templates/bookmark/bookmark_detail.html
{% extends "common/base.html" %}
{% load tagging_tags %}

{% block title %}북마크 상세{% endblock %}

{% block content %}

    <h1>Bookmark Detail</h1>

    <p>사이트 : {{bookmark_detail.title}}</p>
    <p>도메인 : <a href="http://{{bookmark_detail.url}}">{{bookmark_detail.url}}</a></p>


    <div>
        <p>TAG</p>
        <p>
            {% tags_for_object object as tags %}
            {% for tag in tags %}
            <a href="{% url 'bookmark:tag_object_list' tag.name %}">{{tag.name}}</a>
            {% endfor %}
            <a href="{% url 'bookmark:tag_cloud' %}">tag cloud</a>
        </p>
    </div>
{% endblock %}

bookmark/templates/bookmark/bookmark_list.html
{% extends "common/base.html" %}
{% load staticfiles %}

{% block service_style %}
<link rel="stylesheet" href="{% static "style/bookmark/list.css" %}">
{% endblock %}
{% block title %}북마크 리스트{% endblock %}

{% block content %}
    <h1>Bookmark List</h1>

    <ul>
        {% for bookmark in bookmark_list %}
        <li>
            <a href="{% url 'bookmark:detail' bookmark.id %}">{{bookmark.title}}</a>
        </li>
        {% endfor %}
    </ul>
{% endblock %}

bookmark/templates/bookmark/main.html
{% extends "common/base.html" %}
{% load staticfiles %}
{% block title %}북마크 메인{% endblock %}
{% block service_style %}
<link rel="stylesheet" href="{% static "style/bookmark/main.css" %}">
{% endblock %}

{% block content %}
    <h1>Bookmark 메인</h1>
{% endblock %}

bookmark/templates/bookmark/tag_cloud.html
{% extends "common/base.html" %}
# load staticfiles는 static파일이 사용되는 각 템플릿 파일마다 load해 줘야함
{% load staticfiles %}
{% load tagging_tags %}

{% block title %} tag cloud! {% endblock %}

# load staticfiles 는 베이스에 해두면 되지 않나?
{% block extrastyle %}{% static 'style/common/tag.css' %}{% endblock %}

{% block content %}
<h1>Bookmark Tag Cloud</h1>

<!--# tagging패키지의 tag_cloud_for_model커스텀 태그를 사용해 태그 클라우드 표현방식 정의-->
{% tag_cloud_for_model bookmark.Bookmark as tags with steps=6 min_count=1 distribution=log %}
  {% for tag in tags %}
  <p class="tag-{{tag.font_size}}">
    <a href="{% url 'bookmark:tag_object_list' tag.name %}">{{tag.name}}</a>
  </p>
  {% endfor %}
{% endblock %}

bookmark/templates/bookmark/tag_list.html
{% extends "common/base.html" %}
{% load tagging_tags %}

{% block title %} '{{tag.name}}'-Tag Post List {% endblock %}

{% block content %}
<h1>'{{tag.name}}'-Tag Post List</h1>

{% for bookmark in object_list %}
  <h2><a href="{% url 'bookmark:detail' bookmark.id %}">{{bookmark.title}}</a></h2>
{% endfor %}
{% endblock %}